<a href="https://colab.research.google.com/github/vedasreedasi/veda700750192/blob/main/700750192_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vedasree Dasi
700750192

1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [2]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Venkat", "Uppalapati", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Uppalapati", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nandhu", "Nandini", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [10]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 3.57724456  4.75743833 18.87782382  8.83349523  9.73843663 13.23329184
  4.25293022  3.0982812   6.90727422 12.72797731 13.02934518  4.92640709
 19.63440597 10.95519379 15.01036469 19.91994945  4.71061571  2.34265631
 15.84361188 11.23998582]


In [11]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 3.57724456  4.75743833 18.87782382  8.83349523  9.73843663]
 [13.23329184  4.25293022  3.0982812   6.90727422 12.72797731]
 [13.02934518  4.92640709 19.63440597 10.95519379 15.01036469]
 [19.91994945  4.71061571  2.34265631 15.84361188 11.23998582]]


In [12]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 3.57724456  4.75743833  0.          8.83349523  9.73843663]
 [ 0.          4.25293022  3.0982812   6.90727422 12.72797731]
 [13.02934518  4.92640709  0.         10.95519379 15.01036469]
 [ 0.          4.71061571  2.34265631 15.84361188 11.23998582]]
