<a href="https://colab.research.google.com/github/vedasreedasi/veda700750192/blob/main/700750192_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vedasree Dasi
700750192

1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Venkat", "Uppalapati", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Uppalapati", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nandhu", "Nandini", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [3]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [15.50591638 16.88033999  7.1725857  12.84373112  5.07127572  6.44276621
 13.09780956 11.53139217  2.03278514 14.1403063   8.96398196  9.65939438
  2.53133964 17.61930175  7.78811115 13.85454766  4.22122882  2.10933116
  6.96431274  8.16512082]


In [4]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[15.50591638 16.88033999  7.1725857  12.84373112  5.07127572]
 [ 6.44276621 13.09780956 11.53139217  2.03278514 14.1403063 ]
 [ 8.96398196  9.65939438  2.53133964 17.61930175  7.78811115]
 [13.85454766  4.22122882  2.10933116  6.96431274  8.16512082]]


In [5]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[15.50591638  0.          7.1725857  12.84373112  5.07127572]
 [ 6.44276621 13.09780956 11.53139217  2.03278514  0.        ]
 [ 8.96398196  9.65939438  2.53133964  0.          7.78811115]
 [ 0.          4.22122882  2.10933116  6.96431274  8.16512082]]
